#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# grow_crop - runs germinate on a specific seed and puts the result in
#             the corresponding crop
#
# usage: grow_crop project.repo.dist.arch
#
# This script is just a convenient wrapper for `germinate` which is a 
# utility that makes it relatively easy to create a list of all the packages
# that are required to create a local mirror.
#
# This script is fairly tolerant of where it is executed from - it uses the
# file path to determine the top level of the directory where it expects
# to find the directories it needs.
#
# ./seeds/ - where the project specific seed files live
# ./farms/ - where the project specific germinate options live
# ./crops/ - where the project specific output goes (can be deleted later)
#
# Under each of these directories, we put a project specific directory that
# holds the actual files. The naming convention for the project is:
#
# project.repo.rel.arch/
#
# project - the name of the project you want to generate crops for
# repo    - the name of the repo you'll be pulling packages from
# rel     - the release in the repo
# arch    - the architecture of the target
#
# This seems awfully complicated, but there's a good reason for it. In
# the original use I had for a list of packages, I was creating a local
# partial mirror of Debian Jessie for the armel architecture. It turns 
# out that I also needed to get packages from the official Debian
# repos as well as a third party repo. On top of that, the distribution
# that I was targeting switched from `wheezy` to `jessie` - and I needed
# to handle amd64 and armel variants.
#
# I realized that I might want to make local partial mirrors for different
# projects I was working on, and maybe even for different architectures.
#
# So it seems complicated, but it's a general solution to my problem.
#
# Copyright (C) 2014-2015 Ralph Hempel <rhempel@hempeldesigngroup.com>
#
# See LICENSE for https://github.com/rhempel/growrepo
# -----------------------------------------------------------------------------

set -e

# ---------------------------------------------------------------------------
# Make sure we're being called as `grow_crop` and that the folders we need
# exist

SOURCE_ROOT="${BASH_SOURCE%/grow_crop}"

. ${SOURCE_ROOT}/bashtools/src/fmt
. ${SOURCE_ROOT}/bashtools/src/checkutil

LOG_LEVEL="4"

# -----------------------------------------------------------------------------

info "Executing $0"

[[ -z "$1" ]] && fail "Usage: grow_crop project.repo.dist.arch"

# -----------------------------------------------------------------------------
# Check to make sure we are not running as the root or reprepro user

checknotuser "root"
checknotuser "reprepro"

SEED="${SOURCE_ROOT}/seeds/$1"
FARM="${SOURCE_ROOT}/farms/$1"
CROP="${SOURCE_ROOT}/crops/$1"

checkemptyvar "SEED"
checkemptyvar "FARM"
checkemptyvar "CROP"

[[ -d "${SEED}"      ]] || fail "${SEED} -> seed directory does not exist"
[[ -d "${FARM}"      ]] || fail "${FARM} -> farm directory does not exist"
[[ -e "${FARM}/conf" ]] || fail "${FARM}/conf -> farm/conf does not exist"

# ---------------------------------------------------------------------------
# Now source the project specific farm parameters, set up variables and 
# run germinate - there are no default values, everything MUST be defined

. "${FARM}/conf"

[[ -d "${CROP}" ]] || mkdir -p "${CROP}"
[[ -d "${CROP}" ]] || fail "${CROP} -> cannot create crop directory"

cd "${CROP}"

checkemptyvar "MIRROR"
checkemptyvar "PROJ"
checkemptyvar "REPO"
checkemptyvar "DIST"
checkemptyvar "REL"
checkemptyvar "ARCH"
checkemptyvar "COMPONENTS"

# NOTE WELL that we don't add quotes around ${OPTIONS} because it might be
#           a list of options. If you put quotes around it then it's passed
#           to germinate as a single option that it can't understand
#
# NOTE WELL that germinate uses the term distribution to refer to what I am
#           calling releases ${REL} in the scripts I use to build mirrors.
#           We use dstribution ${DIST} to refer to the top level Linux
#           distribution name, like debian or ubuntu.

germinate -S "file://${PWD}/../../seeds/" \
          -s "$1"                         \
          -m "${MIRROR}"                  \
          -d "${REL}"                     \
          -a "${ARCH}"                    \
          -c "${COMPONENTS}"              \
              ${OPTIONS}

# ------------------------------------------------------------------------------
info "Done" 
# ------------------------------------------------------------------------------
