#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# harvest_crop - Looks for the specified crop and spits out a list of
#                packages suitable to be used as a filter for reprepro
#
# usage: harvest_crop project.repo.dist.arch crop[s]
#
# NOTE - this script MUST be run as the `reprepro` user - use:
#
# sudo -u reprepro bash
#
# Copyright (C) 2014-2015 Ralph Hempel <rhempel@hempeldesigngroup.com>
#
# See LICENSE for https://github.com/rhempel/growrepo
# -----------------------------------------------------------------------------

set -e

# ---------------------------------------------------------------------------
# Make sure we're being called as `harvest_crop` and that the folders we need
# exist

[[ -z "$1" ]] && fail "Usage: harvest_crop project.repo.rel.arch crop[s]"

SOURCE_ROOT="${BASH_SOURCE%/harvest_crop}"

. ${SOURCE_ROOT}/bashtools/src/fmt
. ${SOURCE_ROOT}/bashtools/src/checkutil

LOG_LEVEL="4"

# -----------------------------------------------------------------------------

info "Executing $0"

# -----------------------------------------------------------------------------
# Check to make sure we are running as the reprepro user

checkuser "reprepro"

FARM="${SOURCE_ROOT}/farms/$1"
CROP="${SOURCE_ROOT}/crops/$1"

checkemptyvar "FARM"
checkemptyvar "CROP"

[[ -d "${FARM}" ]] || fail "\"${FARM}\" -> farm directory does not exist"
[[ -d "${CROP}" ]] || fail "\"${CROP}\" -> crop directory does not exist"

# ---------------------------------------------------------------------------
# Now source the project specific farm parameters, set up variables and 
# run germinate - there are no default values, everything MUST be defined

. "${FARM}/conf"

checkemptyvar "PROJ"
checkemptyvar "REPO"
checkemptyvar "DIST"
checkemptyvar "REL"
checkemptyvar "ARCH"

PRRA="${PROJ}.${REPO}.${REL}.${ARCH}"

[[ "$1" = "${PRRA}"           ]] || fail "\"$1\" does not match conf \"${PRRA}"\"

[[ -d "/srv/reprepro/${PRRA}" ]] || fail "\"/srv/reprepro/${PRRA}\" -> repo directory does not exist"

# ---------------------------------------------------------------------------
# Now apply the magic formula to the crop to get a list of packages, but
# first shift $1 (the farm name) out of the way...

info "Creating package list for \"${PRRA}\""

shift

[[ -z "$1" ]] && fail "At least one crop must be specified"

for c in "$@"; do
    for p in $(cat "${CROP}/$c" \
               | tail -n +3 \
               | head -n -2 \
               | cut -d '|' -f 1); do\
        PACKAGES="${PACKAGES}${PACKAGES+\n}$p install"
    done
done

# ---------------------------------------------------------------------------

info "Writing package list to \"/srv/reprepro/${PRRA}/packages\""

echo -e "${PACKAGES}" > "/srv/reprepro/${PRRA}/packages" 

# ---------------------------------------------------------------------------

info "Updating packages for \"${REPO}\" - this may take a while"

cd "/srv/reprepro/${PRRA}"

reprepro -V update ${REL}

# ------------------------------------------------------------------------------
info "Done" 
# ------------------------------------------------------------------------------
